import Head from "next/head";

export default function signin() {
  return <>
        <Head>
            <title>Login To Your Account</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>signin</div>
    </>
}
